"""Research Workbench V2 control plane.

The package owns registry, preflight and durable-run orchestration. Research
algorithms remain in ``app.services`` so this layer cannot drift their rules.
"""

from app.research.contracts import (
    PARAMETER_MODELS,
    RESEARCH_CONTRACT_SCHEMA,
    BlockingReason,
    CancellationToken,
    CatalogEntry,
    CohortEstimate,
    DataRequirement,
    DataRequirementKind,
    DataStatus,
    EngineeringStatus,
    ErrorBody,
    EventEnvelope,
    EventTableRow,
    FactorCategory,
    FactorDetail,
    FactorId,
    JobStatus,
    NormalizedResearchResult,
    ParameterField,
    PreflightRequest,
    PreflightResult,
    PreflightSource,
    ProgressReporter,
    PromotionStatus,
    ResearchVerdict,
    ResourceEstimate,
    ResultProfile,
    RunAccepted,
    RunCreateRequest,
    RunLinks,
    RunPatch,
    RunRecord,
    RunScopeModel,
    RunScopeType,
    SeriesKind,
    SSEEventType,
    normalize_symbols,
)

__all__ = [
    "PARAMETER_MODELS",
    "RESEARCH_CONTRACT_SCHEMA",
    "BlockingReason",
    "CancellationToken",
    "CatalogEntry",
    "CohortEstimate",
    "DataRequirement",
    "DataRequirementKind",
    "DataStatus",
    "EngineeringStatus",
    "ErrorBody",
    "EventEnvelope",
    "EventTableRow",
    "FactorCategory",
    "FactorDetail",
    "FactorId",
    "JobStatus",
    "NormalizedResearchResult",
    "ParameterField",
    "PreflightRequest",
    "PreflightResult",
    "PreflightSource",
    "ProgressReporter",
    "PromotionStatus",
    "ResearchVerdict",
    "ResourceEstimate",
    "ResultProfile",
    "RunAccepted",
    "RunCreateRequest",
    "RunLinks",
    "RunPatch",
    "RunRecord",
    "RunScopeModel",
    "RunScopeType",
    "SSEEventType",
    "SeriesKind",
    "normalize_symbols",
]
