"""Resolve per-user storage without leaking identity into shared calculations."""

from __future__ import annotations

from pathlib import Path

from app.services.user_context import get_current_user

LEGACY_USER_DIR = "user_data"


def users_root(data_dir: Path) -> Path:
    return data_dir / "users"


def user_dir(data_dir: Path, user_id: str) -> Path:
    # IDs are generated by the registry and constrained to a safe filename.
    if not user_id or user_id in {".", ".."} or "/" in user_id or "\\" in user_id:
        raise ValueError("invalid user id")
    path = users_root(data_dir) / user_id
    path.mkdir(parents=True, exist_ok=True)
    return path


def current_user_dir(data_dir: Path, *, allow_legacy: bool = True) -> Path:
    user = get_current_user()
    if user is None:
        if allow_legacy:
            admin_path = users_root(data_dir) / "admin"
            path = admin_path if admin_path.exists() else data_dir / LEGACY_USER_DIR
            path.mkdir(parents=True, exist_ok=True)
            return path
        raise RuntimeError("authenticated user context is required")
    return user_dir(data_dir, user.id)


def path_for(data_dir: Path, filename: str, *, allow_legacy: bool = True) -> Path:
    return current_user_dir(data_dir, allow_legacy=allow_legacy) / filename
